### PR TITLE
Use the Prometheus exporter-toolkit

### PR DESCRIPTION
**Pull request by SuperQ**
Use the Prometheus exporter-toolkit web package to handle TLS and basic
auth configuration.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
Hey @DRuggeri, just checking on this oull. Should it be updated to the latest exporter-toolkit verison?

**Comment by otakup0pe** [comment]
Stumbling across this looking into an thing where the exporter does not seem to do any verification of client tls certs. Pretty sure that the exporter toolkit handles that fine.

**Review by DaAwesomeP — CHANGES_REQUESTED** [review]
@SuperQ looks like the Go version needs to be updated for some CI steps.

**Comment by SuperQ** [comment]
Yea, I need to double check this patch.

I don't actually use NUT anymore, so I have no way to test this.

**Comment by DaAwesomeP** [comment]
> I don't actually use NUT anymore, so I have no way to test this.

Assuming you still have it installed somewhere there is the dummy UPS for testing: https://networkupstools.org/docs/man/dummy-ups.html I have used it a few times specifically to test monitoring/alerts.

**Comment by DaAwesomeP** [comment]
@otakup0pe CI build is not working yet but if you checkout @SuperQ's branch [`SuperQ:exporter-toolkit`](https://github.com/SuperQ/nut_exporter/tree/exporter-toolkit) then you should be able to build and test it.

**Comment by DRuggeri** [comment]
Recently my [suggestion to enhance the toolkit](https://github.com/prometheus/exporter-toolkit/issues/78) was rejected which leaves this exporter in a difficult spot: implement a breaking change for users (some CLI arguments and env variables that work today would no longer work).

Happy to take a look at #32 since that's a bug, but I don't wish to force a breaking change on users without some sort of clear benefit to them.

**Comment by DRuggeri** [comment]
@otakup0pe and @DaAwesomeP - FYI, this still lives in branch PR-13

I'll fold these updates in to add support for TLS client auth as mentioned in #32 but have a PR out to improve doco on the toolkit before including

**Pull request closed without merging**
